# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TvShows' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TvShows
  pod 'MVICocoa', :git => "https://github.com/droideveloper/MVICocoa.git", :branch => "master"
  pod 'SwinjectStoryboard'
  pod 'Kingfisher', '~> 5.0'
  pod 'RxGesture'

  target 'TvShowsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TvShowsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
